// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Content;
using Volo.Blogging.Files;

// ReSharper disable once CheckNamespace
namespace Volo.Blogging;

public interface IFileAppService : IApplicationService
{
    Task<RawFileDto> GetAsync(string name);

    Task<IRemoteStreamContent> GetFileAsync(string name);

    Task<FileUploadOutputDto> CreateAsync(FileUploadInputDto input);
}
