// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using Volo.Blogging.Admin.Blogs;

// ReSharper disable once CheckNamespace
namespace Volo.Blogging.Admin.Blogs;

public class UpdateBlogDto
{
    public string Name { get; set; }

    public string ShortName { get; set; }

    public string Description { get; set; }

    public string ConcurrencyStamp { get; set; }
}
