// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using Volo.Blogging.Tagging.Dtos;

// ReSharper disable once CheckNamespace
namespace Volo.Blogging.Tagging.Dtos;

public class GetPopularTagsInput
{
    public int ResultCount { get; set; }

    public int? MinimumPostCount { get; set; }
}
