// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Blogging.Blogs;
using Volo.Blogging.Blogs.Dtos;

// ReSharper disable once CheckNamespace
namespace Volo.Blogging;

public interface IBlogAppService : IApplicationService
{
    Task<ListResultDto<BlogDto>> GetListAsync();

    Task<BlogDto> GetByShortNameAsync(string shortName);

    Task<BlogDto> GetAsync(Guid id);
}
